---
- hosts: all
  tasks:
  - name: Add Stack user
    user:
      name: stack
      append: yes
      groups: "{{ 'wheel' if ansible_os_family == 'RedHat' else '' }}"
      shell: "/bin/bash"
    become: yes
    become_user: root
  - name: Add Stack to Sudoers
    lineinfile: dest=/etc/sudoers.d/stack line="stack ALL=(ALL) NOPASSWD:ALL" state=present create=yes
    become: yes
    become_user: root
  - name: Install public key for Stack
    authorized_key:
      user: stack
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    become: yes
    become_user: stack
  - name: Install .bashrc
    copy: src="~/.bashrc" dest=/home/stack/.bashrc
    become: yes
    become_user: stack
  - name: Install .gitconfig
    copy: src="~/.gitconfig" dest=/home/stack/.gitconfig
    become: yes
    become_user: stack
  - name: Test if custom .tmux.conf exist
    stat: path="~/.tmux.conf"
    register: tmux_conf_stat
  - name: Install .tmux.conf (user)
    copy: src="~/.tmux.conf" dest=/home/stack/.tmux.conf
    when: tmux_conf_stat.stat.exists == True
    become: yes
    become_user: stack
  - name: Install .tmux.conf (default)
    copy: src="../common/confs/.tmux.conf" dest=/home/stack/.tmux.conf
    when: tmux_conf_stat.stat.exists == False
    become: yes
    become_user: stack
  - name: Install .vimrc
    copy: src="~/.vimrc" dest=/home/stack/.vimrc
    become: yes
    become_user: stack
